name: gcloud
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Add Database Details
        run: |
          /usr/bin/curl -o FirstProject/database.py \
          --header "Authorization: token ${{ secrets.TOKEN }}" \
            --header "Accept: application/vnd.github.v3.raw" \
              --remote-name \
                --location https://api.github.com/repos/AshishBhoi/private/contents/database.py
      - name: Add Google Storage Details
        run: |
          /usr/bin/curl -o users/google-storage-api.json \
          --header "Authorization: token ${{ secrets.TOKEN }}" \
            --header "Accept: application/vnd.github.v3.raw" \
              --remote-name \
                --location https://api.github.com/repos/AshishBhoi/private/contents/google-storage-api.json
      - name: https redirect
        run: echo SECURE_SSL_REDIRECT = True >> FirstProject/settings.py && echo DEFAULT_FILE_STORAGE = "'storages.backends.gcloud.GoogleCloudStorage'" >> FirstProject/settings.py && echo GS_BUCKET_NAME = "'django1'" >> FirstProject/settings.py
      - name: pip packages
        run: pip3 install --upgrade setuptools && pip3 install -r requirements.txt
      - name: node packages
        run: mkdir blog/static && npm install @fortawesome/fontawesome-free --prefix blog/static && npm install bootstrap --prefix blog/static && npm install jquery --prefix blog/static && npm install popper.js --prefix blog/static
      - name: collectstatic
        run: python3 manage.py collectstatic
      - name: create migration
        run: python3 manage.py makemigrations && python3 manage.py migrate
      - uses: exelban/gcloud@master
        env:
          PROJECT_ID: ${{secrets.PROJECT_ID}}
          APPLICATION_CREDENTIALS: ${{secrets.SERVICE_ACCOUNT}}
        with:
          args: app deploy app.yaml
      - name: delete secrets
        run: rm FirstProject/database.py && rm users/google-storage-api.json